spring:
  application:
    name: chat
  data:
    mongodb:
      username: subha
      password: subha
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
server:
  port: 8088
